### ISSUE TITLE
Customize htmlbeautifier execution arguments

### ISSUE THREAD

**Issue by hackhowtofaq** [aliariff/vscode-erb-beautify#1]
Hello and thanks for this plugin!

Do you have any plans to support custom execution arguments?

E.g. a settings option to edit the htmlbeautifier command line options, say, `htmlbeautifier -b 4`

Ty!

**Comment by aliariff** [comment]
Hi,

Yes that is possible, I will try as soon I have free time.

Thanks for the input.
