### ISSUE TITLE
couldn't find htmlbeautifier for formatting (ENOENT)

### ISSUE THREAD

**Issue by harssh** [aliariff/vscode-erb-beautify#11]
Could not find htmlbeautifier even if its installed.
```
which htmlbeautifier
/Users/devuser/.rvm/gems/ruby-2.6.3/bin/htmlbeautifier
```

**Comment by aliariff** [comment]
Hi @harssh 

Could you run `htmlbeautifier` from the VSCode built-in terminal?

**Comment by harssh** [comment]
Yes @aliariff ,
No error while executing from terminal

**Comment by aliariff** [comment]
@harssh 
could you try to install it globally:
`rvm @global do gem install htmlbeautifier`

if still not working, maybe this is related to the environment to load the bin`PATH`

**Comment by harssh** [comment]
Working no thanks

**Comment by pruzicka** [comment]
I have the same problem, but with rbenv. I have htmlbeautifier in gem file, also under current ruby gems collections.  Still doesn't work and I got ENOENT. Could you please add path variable to extension configuration? That would help.
Thank you

**Comment by spiman** [comment]
@pruzicka quickest way to hack around this it to link the rbenv shim to a directory in the default PATH (e.g. `/usr/local/bin/htmlbeautifier`), but a way to supply the htmlbeautifier executable path would be much better

**Comment by AsgharMultiplexGraphics** [comment]
Error occurred while formatting: Command failed with exit code 1
