### ISSUE TITLE
When I run 'Format Document', 'ruby' pop up on my Activity Monitor and takes up 99% of my CPU

### ISSUE THREAD

**Issue by Kyle-Law** [aliariff/vscode-erb-beautify#12]
This happens whenever the formatter is run:

![image](https://user-images.githubusercontent.com/55923773/102578750-da82a800-4135-11eb-8e5c-e3779153aa4c.png)

I wonder if it's happening to me only or if anyone faces this issue as well?

**Comment by aliariff** [comment]
Hi all,
The latest release fixed this issue. Would you please update the extension on your vscode?
If still there is an issue, please create one.
