### ISSUE TITLE
can't find htmlbeautifier MACOS

### ISSUE THREAD

**Issue by ViciousMagician** [aliariff/vscode-erb-beautify#13]
When running format document get this message.

couldn't find htmlbeautifier for formatting (ENOENT)

htmlbeautifier show.html.erb works from command line

**Comment by ViciousMagician** [comment]
Solved this, sorry for opening issue too soon. 

Caused by having RVM.  remove htmlbeautifier and install from / sudo gem install htmlbeautifier now all works.

**Comment by rromanchuk** [comment]
@ViciousMagician  that's a bug

**Comment by BobWalsh** [comment]
having the same issue after @ViciousMagician 's fix.
uninstalled htmlbeautifier from gemfile, and from rvm.
installed via sudo htmlbeautifier
restarted vs code
still getting `couldn't find htmlbeautifier for formatting (ENOENT)` on every save and when I format document.

**Comment by jdmartinez1062** [comment]
Had the same issue, the gem was working properly for a couple of weeks then suddenly stopped working. Did the sudo gem install with out uninstalling the rvenb version and now it is working properly.

**Comment by toekneema** [comment]
awesome thank you! 
SOLUTION: run `sudo gem install htmlbeautifier`

**Comment by SuperAndreyEG** [comment]
tried all suggested above solutions and still getting the error

couldn't run htmlbeautifier 'spawn htmlbeautifier ENOENT'

**Comment by aliariff** [comment]
@SuperAndreyEG 
you can set the binary path directly using `vscode-erb-beautify.executePath` setting.
locate `htmlbeautifier` binary using `which htmlbeautifier` command.

**Comment by aliariff** [comment]
in case you are running it with bundler, you can also set the settings.
ref: https://github.com/aliariff/vscode-erb-beautify#settings

**Comment by SuperAndreyEG** [comment]
@aliariff thank you for reply, the path has been set to one returned by **which** and now the error is `failed with exit code: 127. 'bundler: command not found: htmlbeautifier Install missing gem executables with `bundle install` '` though gem is installed

**Comment by aliariff** [comment]
have you try this one?
https://stackoverflow.com/questions/26247926/how-to-solve-usr-bin-env-ruby-executable-hooks-no-such-file-or-directory

**Comment by SuperAndreyEG** [comment]
@aliariff thank you it resolved the issue

**Comment by delCatta** [comment]
I added to my `settings.json` the results I got from `which bundler` and `which htmlbeautifier`:

```
  "vscode-erb-beautify.bundlerPath": "/Users/catta/.rbenv/shims/bundler"
  "vscode-erb-beautify.executePath": "/Users/catta/.rbenv/shims/htmlbeautifier"
```

**Comment by rehanmunir** [comment]
I figure-out the solution the problem here is, VS code is not getting the correct ruby version along which htmlbeautifier is installed. We need to install htmlbeautifier in global ruby version

This worked for  me

sudo rvm @global do gem install htmlbeautifier

**Comment by jdempcy** [comment]
@mikong I use chruby and what works for me is opening VS Code from within the directory of my project with `code .`. If I open code elsewhere it does not pick up HTML Beautifier.

**Comment by jdempcy** [comment]
When I run `which htmlbeautifier` from within the project directory I get `/Users/jdempcy/.gem/ruby/3.1.4/bin/htmlbeautifier` which makes sense as I am in a Ruby 3.1.4 project. If I run `which htmlbeautifier` from outside of the project directory I get `htmlbeautifier not found`.

So, I have to make sure that I open VS Code with `code .` from within the project dir, then it all works.

**Comment by jdempcy** [comment]
For those who do not have the shell command `code` added to their shell, you can hit CMD+Shift+P from within VS Code and search for `Shell Command: Install 'code' command in PATH`. If you get an error, first run the uninstall variant, `Shell Command: Uninstall 'code' command in PATH`, then reinstall. Once you have `code` accesible in your shell you can open VS Code from the command line in your project with `code .`.

**Comment by gabrieljablonski** [comment]
After trying all solutions, was still getting the error, even after `Reload window`. Closing VSCode fully and reopening fixed it.
