### ISSUE TITLE
It only works when saving the file, not when pressing Alt + Shift + F

### ISSUE THREAD

**Issue by brunoprietog** [aliariff/vscode-erb-beautify#15]
Hello, basically the error is the title of the issue. When I use the default VS Code command to format the file absolutely nothing happens. If I press CTRL + S it formats the code fine. Is there any way to fix this so that it works with both possible ways?

Thanks!

**Comment by aliariff** [comment]
Hi @brunoprietog,
The latest release fixed this issue. Would you please update the extension on your vscode?
If still there is an issue, please create one.
