### ISSUE TITLE
Stuck forever when formatting erb file

### ISSUE THREAD

**Issue by EnziinSystem** [aliariff/vscode-erb-beautify#19]
Hello,

I install ERB Formatter/Beautify plugin in VS Code and format the attachment file, but it stuck forever with heavy CPU and over heat.

Please use the attached file for a test.

[show.html.zip](https://github.com/aliariff/vscode-erb-beautify/files/7492018/show.html.zip)

**Comment by aliariff** [comment]
Hi @EnziinSystem 
Have you tried formatting the file directly from the command line?
Follow: https://github.com/threedaymonk/htmlbeautifier#from-the-command-line

**Comment by EnziinSystem** [comment]
Yes, when running the command:
```
htmlbeautifier app/views/...file_name.html.eb
```
It stuck forever in terminal command.
