### ISSUE TITLE
Self closing tags

### ISSUE THREAD

**Issue by julianleahy** [aliariff/vscode-erb-beautify#2]
Hi, this is a great plugin - I have one small issue - if the tag is self closing (<img ... / >) is screws up the formatting (It's fine if I do this <img ...>)

**Comment by aliariff** [comment]
Hi, this issue I think is more related with the gem itself, you might want to create issue over there.

https://github.com/threedaymonk/htmlbeautifier

This extension is just a wrapper to make that gem work in vscode
