### ISSUE TITLE
Formatting incorrect when setting attributes

### ISSUE THREAD

**Issue by j-manu** [aliariff/vscode-erb-beautify#22]
```erb
<% @links.each do |link| %>
  <option <%= link[:selected] ? 'selected' : '' %>>
          <%= link[:name] %>
        </option>
  <% end %>
```

This code does not get formatted correctly.

**Comment by aliariff** [comment]
Hi @j-manu 

- Is there any error message in the vscode console log?
- Have you tried formatting the file directly from the command line?
Follow: https://github.com/threedaymonk/htmlbeautifier#from-the-command-line

**Comment by j-manu** [comment]
* No output in console log
* Formatting from the command line doesn't format the file either. The command runs without error but does not format

**Comment by j-manu** [comment]
I have opened an issue in htmlbeautifier https://github.com/threedaymonk/htmlbeautifier/issues/66 since the fix needs to be there
