### ISSUE TITLE
WSL2 issue

### ISSUE THREAD

**Issue by costinEEST** [aliariff/vscode-erb-beautify#25]
Hi,

How to set up the extension inside of WSL2?

In `C:\Users\Me\AppData\Roaming\Code\User\settings.json`, I added
```json
    "vscode-erb-beautify.bundlerPath": "/home/me/.rbenv/shims/bundler",
    "vscode-erb-beautify.executePath": "/home/me/.rbenv/shims/htmlbeautifier"
```
but it triggers

`
couldn't run /home/me/.rbenv/shims/htmlbeautifier.bat 'spawn /home/me/.rbenv/shims/htmlbeautifier.bat ENOENT'
`

**Comment by brunoprietog** [comment]
You do not need to do anything, just make sure that the extension is installed on remote WSL.
