### ISSUE TITLE
Code inside of a do block is not indented

### ISSUE THREAD

**Issue by overdrivemachines** [aliariff/vscode-erb-beautify#27]
```erb
<%= link_to post, class: "post-container" do %>
<div>
  ...
</div>
<% end %>
```
This plugin does not indent the div inside the do block. Can this be fixed?

**Comment by aliariff** [comment]
Hi @overdrivemachines  

- Is there any error message in the vscode console log?
- Have you tried formatting the file directly from the command line?
Follow: https://github.com/threedaymonk/htmlbeautifier#from-the-command-line

**Comment by aliariff** [comment]
Closing this since it can't be reproduced, and there's no extra info to go on. If the problem's still there, please reopen and share more details.
