### ISSUE TITLE
Document how to format .html.erb files

### ISSUE THREAD

**Issue by mltsy** [aliariff/vscode-erb-beautify#4]
It took me a while to figure out why it wasn't working on my `.html.erb` files, and I discovered I just had to add this to my `settings.json`:

```json
"files.associations": {
  "*.erb": "erb"
}
```
Otherwise it was counting them not as `erb` files, but `html.erb` files - it would be helpful to note this in the installation/config requirements.

**Comment by aliariff** [comment]
Hi yes you are right, thanks for the input.

**Comment by maelfosso** [comment]
Hello @mltsy 
I did it. But it's not working

**Comment by mltsy** [comment]
Maybe if you paste in your `settings.json` file and describe what you are observing that indicates to you that it's "not working", along with what you would expect to see instead, someone can help :)

**Comment by pkim050** [comment]
I have this in the settgins.json file:
"files.associations": {
        "*.erb": "erb"
    }

But I am not sure if it is working. The font just turned all white.

**Comment by aliariff** [comment]
Hi @pkim050 

Could you give a screenshot of the behavior and also the log from the console?
