### ISSUE TITLE
v0.4.0. still unicode characters turns ���

### ISSUE THREAD

**Issue by mana-bin** [aliariff/vscode-erb-beautify#46]
@aliariff  still I have same issue 😢
https://github.com/aliariff/vscode-erb-beautify/issues/44

**Comment by aliariff** [comment]
Hi @mana-bin, could you give an example of the text?
Also, if possible, provide the log information from the vs-code.

**Comment by mana-bin** [comment]
I try to find text, but sometime it turns � sometime does not 😕
Let me research my environment. 

Im not developer of vscode, so I don't know much about logs, can you tell me where logs are?

**Comment by aliariff** [comment]
for the log, you can open the developer tools from the help menu, and you will see the console log information there.
<img width="383" alt="image" src="https://github.com/aliariff/vscode-erb-beautify/assets/6806035/54c654de-9637-4f3b-9f12-5911ed60e8cc">

**Comment by aliariff** [comment]
another option is you can try to set the language & encoding. example:

```json
"vscode-erb-beautify.customEnvVar": {
  "LC_ALL": "en_US.UTF-8"
}
```

try some other values according to your local, like: `ja_JP.UTF-8`, `ja_JP.PCK`, etc

**Comment by mana-bin** [comment]
@aliariff 

here is texts example

```
  <p>(1)前項の定めにかかわらず、本規約に即時に契約解除できるとの定めがあるとき</p>
```


logs
[vscode-app-1687971446008.log](https://github.com/aliariff/vscode-erb-beautify/files/11898179/vscode-app-1687971446008.log)

if I continue saving.
https://github.com/aliariff/vscode-erb-beautify/assets/16030702/2ddfba7d-4c50-4b0e-b80a-50215997901a

its weird,  if I copy this line, and paste to blank file, it seems fine.

**Comment by aliariff** [comment]
Hi @mana-bin,
I have a suspicion about conflicting extensions, could you disable all extensions except this `vscode-erb-beautify` and try to format the file?

Regarding the log you attached, seems not really related at all to this extension.

And for reproducing the issue, you can try to remove the line one by one, until you got a minimum example where the issue consistently occurred.

**Comment by 0q2** [comment]
> another option is you can try to set the language & encoding. example:
> 
> ```json
> "vscode-erb-beautify.customEnvVar": {
>   "LC_ALL": "en_US.UTF-8"
> }
> ```
> 
> try some other values according to your local, like: `ja_JP.UTF-8`, `ja_JP.PCK`, etc

This fixed it for me :)

**Comment by kugelblitz6535** [comment]
This file reproduce problem for me.
Last character "あ" turns "��" after format.

Enabling only `vscode-erb-beautify` and no settings.json.

```html.erb
<div>
  <div>
    あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ
  </div>
</div>

```

**Comment by aliariff** [comment]
Hi @kugelblitz6535 

Thank you, now I can reproduce this issue. I will take a look and fix it.

**Comment by kugelblitz6535** [comment]
I confirmed that it was fixed.
Thank you @aliariff.
