### ISSUE TITLE
Error parsing standard input: invalid byte sequence in US-ASCII 

### ISSUE THREAD

**Issue by witcan** [aliariff/vscode-erb-beautify#47]
<img width="579" alt="image" src="https://github.com/aliariff/vscode-erb-beautify/assets/48895485/ca86f322-cbbf-4644-ab99-6cfcbbfbb8f1">

example:

``` 
<h1>工作项列表</h1>
<button class="btn btn-primary" type="button">Primary</button>
<table>
  <thead>
    <tr>
      <th scope="col">Table header 1</th>
      <th scope="col">Table header 2</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td>Table footer 1</td>
      <td>Table footer 2</td>
    </tr>
  </tfoot>
  <tbody>
    <tr>
      <td>Table data 1</td>
      <td>Table data 2</td>
    </tr>
  </tbody>
</table>

```

**Comment by ashgkwd** [comment]
I also started getting the same error message. 

File contents are:

```erb
<main class="mx-auto">
  <%= render 'shared/screen_title', title: "Thank You ✨" %>
</main>
```
The actual formatting done by `htmlbeautifier` works fine.

```sh
htmlbeautifier path/to/myfile.html.erb
```

Only when the formatting is run through VS Code, it gives this *invalid byte sequence in US-ASCII* error. I also tried using different erb formatters and they all give this error when run through VS Code.

**Comment by aliariff** [comment]
try to add this setting

```json
"vscode-erb-beautify.customEnvVar": {
  "LC_ALL": "en_US.UTF-8"
}
```

**Comment by Duartemartins** [comment]
Thanks, might be worth adding in the Readme!
