### ISSUE TITLE
Ctrl + / does not add comment block

### ISSUE THREAD

**Issue by rsdsllc-com-dipenc** [aliariff/vscode-erb-beautify#50]
When editing a .html.erb file, pressing keys Ctrl + / adds `#` which is not helpful. It should add `<!--  -->` instead which is appropriate because we are writing in HTML.

**Comment by aliariff** [comment]
Hi @rsdsllc-com-dipenc 

This extension doesn't manage commenting functionality. The Ruby LSP manages such tasks. I believe you're utilizing the one available at https://marketplace.visualstudio.com/items?itemName=Shopify.ruby-extensions-pack. The behavior for ERB comments is defined there, so raising your issue in that repository would be more appropriate. The specific line that might relate to your issue can be found here: https://github.com/Shopify/vscode-ruby-lsp/blob/main/languages/erb.json#L3.
