### ISSUE TITLE
plugin forcefully adds final new line (does not respect vscode settings.json)

### ISSUE THREAD

**Issue by burakkgunduzz** [aliariff/vscode-erb-beautify#52]
I would like to have one line of separation when needed in my erb files. I am able to do it with   "vscode-erb-beautify.keepBlankLines": 1 setting. 
However, I do not want to add a blank line at the end of my file when I formatted the file. Regardless of keepBlankLines setting (it does not matter whether it is 0 (default) or 1), I end up finding my file has 1 blank line at the end of it.

I tried to disable this behavior with "files.insertFinalNewline": true, but it does not work. I think the plugin overrides it. Because I managed to work it only when the plugin is disabled.
I am looking forward to a solution for this behavior, thanks!

**Comment by aliariff** [comment]
Hi @burakkgunduzz,

Thanks for raising this issue. I will try to fix this ASAP.
