### ISSUE TITLE
Possible to ignore files or parts in files?

### ISSUE THREAD

**Issue by darkBuddha** [aliariff/vscode-erb-beautify#53]
Hi, I could not find any information regarding this. Is it somehow possible? Thanks

**Comment by aliariff** [comment]
Hi @darkBuddha, do you mean you want to avoid formatting specific files even though you have `formatOnSave: true`?

**Comment by aliariff** [comment]
Hi @darkBuddha

Atm, I have no capacity to improve the plugin. Feel free to contribute a PR.

**Comment by darkBuddha** [comment]
Amazing, thank you!

**Comment by aliariff** [comment]
@darkBuddha please refer to [readme](https://github.com/aliariff/vscode-erb-beautify?tab=readme-ov-file#disabling-formatting-for-specific-files) on how to configure it.
