### ISSUE TITLE
Couldn't run htmlbeautifier 'spawn htmlbeautifier ENOENT'

### ISSUE THREAD

**Issue by Nicklashjortbol** [aliariff/vscode-erb-beautify#55]
Hi - when I edit the settings.json in VSC with the following: 

"[erb]": {
  "editor.defaultFormatter": "aliariff.vscode-erb-beautify",
  "editor.formatOnSave": true
},
"files.associations": {
  "*.html.erb": "erb"
}

and subsequently try to save/format the document, I get the following error(s): 

"Couldn't run htmlbeautifier 'spawn htmlbeautifier ENOENT'" & 
"Error occurred while formatting: spawn htmlbeautifier ENOENT"

Any ideas on what causes this? 

BR Nicklas

**Comment by youyoumu** [comment]
i have the same issue

**Comment by aliariff** [comment]
Hi @Nicklashjortbol @youyoumu please check existing issues at https://github.com/aliariff/vscode-erb-beautify/issues/11 & https://github.com/aliariff/vscode-erb-beautify/issues/13

**Comment by aliariff** [comment]
Please reopen with further information if the previous issues mentioned can't help solve yours.
