### ISSUE TITLE
Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by wengzilla** [aliariff/vscode-erb-beautify#63]
Have recently been getting this error and autoformat no longer works... Any ideas? Originally, I thought it was the new version of the VSCode plugin, but I don't think it is.

![Screenshot 2024-04-01 at 2 02 17 PM](https://github.com/aliariff/vscode-erb-beautify/assets/219947/454bed57-a688-4dbd-a257-0b2877044c7a)

Currently using htmlbeautifier 1.4.3. Also, when I manually run `htmlbeautifier` via the command line, it works.

**Comment by aliariff** [comment]
Hi @wengzilla,

Please update the extension to the latest version. If the issue persists, feel free to reopen this ticket.
