### ISSUE TITLE
No EOF lines added

### ISSUE THREAD

**Issue by MattBudz** [aliariff/vscode-erb-beautify#66]
Typically, it's best practice to have a blank line at the end of the file. This formatter doesn't add that to erb files by default. Is there an option to enable this or would it be a feature request?

**Comment by aliariff** [comment]
Duplicate https://github.com/aliariff/vscode-erb-beautify/issues/52

You can set it via `"files.insertFinalNewline": true`

**Comment by MattBudz** [comment]
Confirmed, adding `"files.insertFinalNewline": true` to settings.json results in the expected output. Thanks for you help @aliariff and keep up the great work! 🙏💪
