### ISSUE TITLE
Not working with non ascii on MacOSX

### ISSUE THREAD

**Issue by mekku** [aliariff/vscode-erb-beautify#8]
I found the issue with the files that contain non-ASCII characters.
When I try to format them, nothing happens.
After investigated, I found a way to fix it. You need "LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8" before run htmlbeautifier.
`const beautify = cp.spawn(``LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8 htmlbeautifier${ext}``, [
                    ...options,
                    document.uri.fsPath
                ], {
                    shell: true
                });`

**Comment by aliariff** [comment]
if that the case, I think you can try to change this only for your environment
```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**Comment by mekku** [comment]
> if that the case, I think you can try to change this only for your environment
> 
> ```
> export LANG=en_US.UTF-8
> export LANGUAGE=en_US.UTF-8
> export LC_ALL=en_US.UTF-8
> ```

How I do thai?
I put it in ~/.profile but not working.

**Comment by ouven** [comment]
I also hit the problem with de_DE.UTF-8. Maybe there is a way to set the editor tab' encoding. Any Idea?

**Comment by aliariff** [comment]
Hi all,
The latest release fixed this issue. Would you please update the extension on your vscode?
If still there is an issue, please create one.
