### ISSUE TITLE
Problem when I launch the command "Format Document"

### ISSUE THREAD

**Issue by theodugautier** [aliariff/vscode-erb-beautify#9]
Hi, 

When I run the command `Format Document` while I am in a `.html.erb` file, nothing happens, there is just a file that is created. For example, if I run the command in a file called `_small_panels.html.erb`, a file will be created called `_small_panels.html.erb.tmp` and that's it.

![Capture d’écran 2019-09-11 à 11 15 29](https://user-images.githubusercontent.com/16017408/64684545-92ca9680-d485-11e9-9a0a-5cc2461922af.png)

my settings.json
```
{
    "workbench.colorTheme": "Gruvbox Dark Medium",
    "workbench.iconTheme": "material-icon-theme",
    "editor.fontSize": 15,
    "emmet.includeLanguages": { "erb": "html" },
    "files.associations": {
        "*.erb": "erb"
    }
}
```

Thank !

**Comment by rafaltrojanowski** [comment]
Hmm, maybe try to figure out on smaller file? I had the same issue.

**Comment by jmschp** [comment]
I have the same problem, but it only seems to happen in big files.

**Comment by theodugautier** [comment]
@jmschp Now I use a custom spot in vs code to format ERB automatically.

https://medium.com/@costa.alexoglou/enable-formatting-with-erb-files-in-vscode-d4b4ff537017

And you can add customs configurations (see documentation https://github.com/threedaymonk/htmlbeautifier) : 
`"command": "ext=$(echo ${file})  && if [ ${ext##*.} == erb ]; then htmlbeautifier ${file} ${file}; else echo 'Not an ERB file'; fi",`

**Comment by qinyuanmao** [comment]
```javascript
        const beautify = spawn(
          `htmlbeautifier${ext}`,
          [document.uri.fsPath, ...options],
          {
            env: {
              ...process.env,
              LC_ALL: 'en_US.UTF-8',
            },
          }
        );
```

**Comment by brunoprietog** [comment]
It only works for me when I save the file

**Comment by aliariff** [comment]
Hi all,
The latest release fixed this issue. Would you please update the extension on your vscode?
If still there is an issue, please create one.
